Quest - sync fails after staying idle in the app for a short period of time
opensrp/fhircore pull request #1126
Opened 2022-03-04 18:36 UTC by owais-vd

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1106 

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Release | Other) 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-03-04 18:42 UTC, pld requested changes
can you please add a test that ideally reproduces the error in the issue and is resolved with these change

2022-03-04 19:34 UTC, owais-vd commented
> can you please add a test that ideally reproduces the error in the issue and is resolved with these change

done

2022-03-04 19:35 UTC, pld approved these changes
lgtm!

2022-03-05 11:31 UTC, merged

2022-03-07 06:57 UTC, ekigamba commented on android/engine/src/main/java/org/smartregister/fhircore/engine/ui/register/BaseRegisterActivity.kt
> +      accountAuthenticator.logout()
This is an issue in the current OpenSRP. Hold off on this awaiting discussions within OpenSRP

2022-03-07 07:01 UTC, ekigamba commented on android/engine/src/main/java/org/smartregister/fhircore/engine/ui/register/BaseRegisterActivity.kt
> +      accountAuthenticator.logout()
See this for more information https://github.com/opensrp/support/issues/108