Add count param
opensrp/fhircore pull request #1128
Opened 2022-03-07 01:34 UTC by FikriMilano

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1119

**Type**
Choose one: Feature

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-03-07 01:58 UTC, FikriMilano commented
@maimoonak  I can't run the app after merging the latest changes, even in the main branch.
The app crashes after submitting the app config name. Either Quest or ANC.

2022-03-07 13:47 UTC, pld requested changes

2022-03-07 13:47 UTC, pld commented on android/engine/src/main/java/org/smartregister/fhircore/engine/di/NetworkModule.kt
> +      .connectTimeout(120, TimeUnit.SECONDS)
let's move these timeouts to constants

2022-03-08 03:04 UTC, FikriMilano commented on android/engine/src/main/java/org/smartregister/fhircore/engine/di/NetworkModule.kt
> +      .connectTimeout(120, TimeUnit.SECONDS)
Okay

2022-03-09 07:16 UTC, ellykits approved these changes

2022-03-10 19:07 UTC, pld commented
> @pld could you approve for this changes? (couldn't merge without it)

apologies for the delay, I've dismissed my stale review, you should be all set now!

2022-03-11 01:14 UTC, merged