Fix report select patient padding issue
opensrp/fhircore pull request #1143
Opened 2022-03-14 13:32 UTC by FikriMilano

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #992

**Type**
Choose one: Bug fix

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-03-14 13:36 UTC, FikriMilano commented
But a new bug crops up if I fix #992 
I need some help @ellykits 

<img src="https://user-images.githubusercontent.com/62053304/158182814-92d4fa80-fe64-47a6-89ed-7e7153bfec7b.png" width="256">

2022-03-16 12:40 UTC, ellykits requested changes

2022-03-16 12:50 UTC, FikriMilano commented on android/anc/src/main/java/org/smartregister/fhircore/anc/ui/report/ReportHomeActivity.kt
> +  @Inject lateinit var jsonSpecificationProvider: AncJsonSpecificationProvider
Sure thing

2022-03-17 07:00 UTC, ellykits approved these changes

2022-03-17 07:02 UTC, merged