1142 remove family member
opensrp/fhircore pull request #1156
Opened 2022-03-22 06:04 UTC by aurangzaibumer

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[issue number] 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-03-22 08:11 UTC, dubdabasoduba requested changes

2022-03-22 08:11 UTC, dubdabasoduba commented on android/anc/src/main/java/org/smartregister/fhircore/anc/ui/details/PatientDetailsActivity.kt
> +//        )
Remove this dead code if you are no longer using it.

2022-03-22 08:11 UTC, dubdabasoduba commented on android/anc/src/main/java/org/smartregister/fhircore/anc/ui/family/form/RemoveFamilyQuestionnaireActivity.kt
> +
Reformat this to remove the extra line.

2022-03-22 08:11 UTC, dubdabasoduba commented on android/anc/src/main/java/org/smartregister/fhircore/anc/ui/family/form/RemoveFamilyQuestionnaireActivity.kt
> +        familyId = intent.extras?.getString(QUESTIONNAIRE_ARG_PATIENT_KEY) ?: ""
@ellykits Same question I have earlier, can we create an object for the family & patient. We can then pass this object to the other classes any time we need to.  Right now we are passing single attributes (which is okay) but will it be too many intent etxras at some point?

2022-03-24 08:24 UTC, dubdabasoduba submitted a review, later dismissed

2022-03-24 18:02 UTC, dubdabasoduba approved these changes

2022-03-30 12:22 UTC, dubdabasoduba submitted a review, later dismissed

2022-05-17 14:24 UTC, ellykits commented
Closing this. Implementation already merged to main via another PR.

2022-05-17 14:24 UTC, closed without merging