1205 Remove family member
opensrp/fhircore pull request #1235
Opened 2022-04-27 02:33 UTC by FikriMilano

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1205

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-04-27 02:33 UTC, FikriMilano commented
cc @dubdabasoduba @ellykits

2022-04-28 09:53 UTC, ellykits requested changes

2022-04-28 09:53 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/family/remove/RemoveProfileQuestionnaireActivity.kt
> +  abstract fun setRemoveDialogMessage(profileName: String): String
Can we use the confirmation dialog from `QuestionnaireActivity` for consistency?

2022-04-28 09:53 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/family/remove/RemoveProfileViewModel.kt
> +abstract class RemoveProfileViewModel<T>
Rename this class accordingly. The current name is a bit confusing.

2022-04-28 09:53 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/family/remove/RemoveProfileViewModel.kt
> +  var isDiscarded = MutableLiveData(false)
These can be wrapped into a view state data class model.

2022-04-28 09:53 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/family/remove/RemoveProfileViewModel.kt
> +  abstract fun remove(profileId: String)
Follow the event pattern.

2022-04-28 09:53 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/family/remove/member/RemoveMemberProfileQuestionnaireActivity.kt
> +class RemoveMemberProfileQuestionnaireActivity : RemoveProfileQuestionnaireActivity<Patient>() {
This class should not be necessary if we use the confirmation dialog from the `QuestionnaireActivity`

2022-04-28 09:53 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/family/remove/member/RemoveMemberProfileQuestionnaireActivity.kt
> +class RemoveMemberProfileQuestionnaireActivity : RemoveProfileQuestionnaireActivity<Patient>() {
Maybe for the viewmodel logic we may need it

2022-04-28 09:53 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/family/remove/family/RemoveFamilyProfileQuestionnaireActivity.kt
> +class RemoveFamilyProfileQuestionnaireActivity : RemoveProfileQuestionnaireActivity<Group>() {
Do we need to override this class? Is it because of the viewmodel logic?

2022-04-28 09:53 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/family/remove/member/RemoveMemberProfileViewModel.kt
> +  override fun remove(profileId: String) {
Add TODO or remove commented code.

2022-04-28 09:53 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/family/remove/RemoveProfileQuestionnaireActivity.kt
> +  }
Avoid one liner function with one call site. Move this one line code to where the function is invoked.

2022-04-28 09:53 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/family/remove/RemoveProfileQuestionnaireActivity.kt
> +  fun onDiscard() {
Avoid one liner function with one call site. Move this one line code to where the function is invoked.

2022-04-28 09:53 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/family/remove/RemoveProfileViewModel.kt
> +abstract class RemoveProfileViewModel<T>
```suggestion
abstract class RemoveFamilyEntityViewModel<T>
```

2022-04-28 13:42 UTC, merged