1345 | ANC care plan
opensrp/fhircore pull request #1359
Opened 2022-06-20 06:42 UTC by maimoonak

Fixes #1345 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-06-23 09:20 UTC, dubdabasoduba requested changes

2022-06-23 09:20 UTC, dubdabasoduba commented on android/quest/src/main/assets/configs/anc/config_forms.json
> +      "identifier": "132152",
Do we have this updated on the fhir-resources repo?

2022-06-23 13:22 UTC, maimoonak commented on android/eir/build.gradle
> +   // implementation 'androidx.legacy:legacy-support-v4:1.0.0'
reverted

2022-06-23 13:22 UTC, maimoonak commented on android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/TaskExtension.kt
> +    this.description.contains("pregnant ", true)
Added it to regex. Added a unit test as well

2022-06-27 11:08 UTC, dubdabasoduba approved these changes

2022-06-27 12:39 UTC, merged