Add ci-mwcore.yml ci workflow
opensrp/fhircore pull request #1368
Opened 2022-06-22 13:19 UTC by LZRS

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-06-22 13:45 UTC, dubdabasoduba requested changes
@LZRS I might be wrong but I think all you need to do is to update the main `ci.yml` file and add the mwcore-dev branch

@ndegwamartin Please advice incase I am wrong

2022-06-22 14:56 UTC, ndegwamartin commented
> @LZRS I might be wrong but I think all you need to do is to update the main `ci.yml` file and add the mwcore-dev branch
> 
> @ndegwamartin Please advice incase I am wrong

I'd recommended a separate file because it seems that _mw-core_ is a separate **`master`** and currently not part of the main project/flavors on FHIR Core. Additionally not sure if it is meant to have some different workflow steps from the others.

If this is meant to be merged to `main` at some point and the _other parts of the workflow_ do not differ, then we can indeed have the branch added in the main ci config file. cc @LZRS

2022-06-22 14:59 UTC, dubdabasoduba submitted a review, later dismissed

2022-06-22 15:00 UTC, dubdabasoduba commented
> > @LZRS I might be wrong but I think all you need to do is to update the main `ci.yml` file and add the mwcore-dev branch
> > @ndegwamartin Please advice incase I am wrong
> 
> I'd recommended a separate file because it seems that _mw-core_ is a separate **`master`** and currently not part of the main project/flavors on FHIR Core. Additionally not sure if it is meant to have some different workflow steps from the others.
> 
> If this is meant to be merged to `main` at some point and the _other parts of the workflow_ do not differ, then we can indeed have the branch added in the main ci config file. cc @LZRS

@ndegwamartin makes sense.

2022-06-23 07:46 UTC, ndegwamartin approved these changes

2022-06-23 07:51 UTC, merged