WIP: test-careplan
opensrp/fhircore pull request #1811
Opened 2022-11-04 10:51 UTC by DebbieArita

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[issue number] 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-11-09 10:37 UTC, dubdabasoduba requested changes

2022-11-09 10:37 UTC, dubdabasoduba commented on android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt
> +
@DebbieArita what are we adding this?

2022-11-22 08:07 UTC, ellykits commented
@DebbieArita Kindly update this PR so we can have it merged.

2022-11-24 18:19 UTC, dubdabasoduba requested changes

2022-11-24 18:19 UTC, dubdabasoduba commented on android/engine/src/test/resources/plans/disease-followup/patient.json
> +}
Do we have a generic sampel patient that this test can use? That way we don't create a new patient resource for every test we write

2022-11-24 18:19 UTC, dubdabasoduba commented on android/quest/src/test/java/org/smartregister/fhircore/quest/StructureMapUtilitiesTest.kt
> +    val map = scu.parse(immunizationStructureMap, "eCBIS Family Registration")
This name doesn't seem right

2022-11-24 18:19 UTC, dubdabasoduba commented
@DebbieArita please add an appropriate title for this PR

2022-12-07 10:18 UTC, dubdabasoduba approved these changes

2022-12-12 17:20 UTC, merged