Add reason for removal
opensrp/fhircore pull request #1839
Opened 2022-11-16 13:11 UTC by DebbieArita

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[issue number] 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-11-16 14:44 UTC, DebbieArita commented on android/quest/src/main/assets/configs/app/profiles/household_profile_config.json
> +                      "data.put('statuses', StringUtils:join([data.get('getChildStatus'), data.get('getSickChildStatus'), data.get('getPregnancyStatus'), data.get('getFPStatus'), data.get('getPNCStat
That's actually not necessary... removing that...

2022-11-18 10:28 UTC, dubdabasoduba commented on android/quest/src/main/assets/configs/app/profiles/household_profile_config.json
> +                      "data.put('statuses', StringUtils:join([data.get('getChildStatus'), data.get('getSickChildStatus'), data.get('getPregnancyStatus'), data.get('getFPStatus'), data.get('getPNCStat
They might be necessary unless we added code to remove trailing spaces and commas.

2022-11-21 09:33 UTC, DebbieArita commented on android/quest/src/main/assets/configs/app/profiles/household_profile_config.json
> +                      "data.put('statuses', StringUtils:join([data.get('getChildStatus'), data.get('getSickChildStatus'), data.get('getPregnancyStatus'), data.get('getFPStatus'), data.get('getPNCStat
@dubdabasoduba... There was an extra one I added by mistake on that line.... that's what I corrected...

2022-11-24 08:08 UTC, ellykits commented on android/quest/src/main/assets/configs/app/profiles/household_profile_config.json
> +                      "data.put('removalReason', fhirPath.extractValue(Patient, Patient.active) == 'false' ? fhirPath.extractValue(Observation, 'Observation.code.text') : '')"                    ]
The profile configuration resources have not been updated to include Observation resource

2022-11-24 18:10 UTC, dubdabasoduba commented on android/quest/src/main/assets/configs/app/profiles/household_profile_config.json
> +                      "data.put('statuses', StringUtils:join([data.get('getChildStatus'), data.get('getSickChildStatus'), data.get('getPregnancyStatus'), data.get('getFPStatus'), data.get('getPNCStat
@ellykits can the work done to remove the trailing comma handle this?

2022-12-05 11:47 UTC, dubdabasoduba requested changes

2022-12-05 11:47 UTC, dubdabasoduba commented on android/quest/src/main/assets/configs/app/profiles/household_profile_config.json
> +                      "data.put('removalReason', fhirPath.extractValue(Patient, Patient.active) == 'false' ? fhirPath.extractValue(Observation, 'Observation.code.text') : '')"                    ]
@DebbieArita is this supposed to be `!=` or `==`. Also, you might not need it based on this https://github.com/opensrp/fhir-resources/blob/main/ecbis_liberia/app_configurations/ecbis_cha_preview/profiles/default_profile_config.json#L53-L59c

2022-12-07 10:20 UTC, dubdabasoduba approved these changes

2022-12-07 12:57 UTC, merged