Update dokka.yml
opensrp/fhircore pull request #1843
Opened 2022-11-18 07:25 UTC by SebaMutuku

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[issue number] 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-11-18 14:36 UTC, pld requested changes

2022-11-18 14:36 UTC, pld commented on .github/workflows/dokka.yml
>          with:
we don't want to overwrite main, just comment out as mentioned here, https://github.com/opensrp/fhircore/issues/1823#issuecomment-1315555032

```suggestion
#      - name: Deploy 🚀
#        uses: JamesIves/github-pages-deploy-action@4.1.4
#        with:
```

2022-11-18 14:36 UTC, pld commented on .github/workflows/dokka.yml
>            folder: android/docs # The folder the action should deploy.
```suggestion
#          branch: gh-pages # The branch the action should deploy to.
#          folder: android/docs # The folder the action should deploy.
```

2022-11-21 09:29 UTC, SebaMutuku commented
Closing this as other alternatives were provided.

2022-11-21 09:29 UTC, SebaMutuku commented
Closing this as other alternatives were provided.

2022-11-21 09:29 UTC, closed without merging