Sequential task parsing
opensrp/fhircore pull request #1854
Opened 2022-11-23 06:22 UTC by maimoonak

Fixes #1696

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-12-15 17:14 UTC, pld reviewed
please also work on getting to past the tests, I know we're gonna pull in a lib we cut, but thinking that's unrelated to failing tests, but lmk if I'm wrong and it makes sense to wait until we've pulled in the lib to address the tests

2022-12-15 17:14 UTC, pld commented on android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt
> +              it.count > i
I don't understand the `let`, but can this fit into a `for` loop structure?

2022-12-15 17:14 UTC, pld commented on android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
> +  fun testGenerateCarePlanForANCVisitWithCql() = runTest {
```suggestion
  fun testGenerateCarePlanForAncVisitWithCql() = runTest {
```

the convention is to not uppercase acronyms, like CQL

2022-12-15 17:14 UTC, pld commented on android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
> +    val lmp = Date().plusMonths(-4).apply { date = 15 }
do we need to test other variations on the lmp date to hit other code-paths / edge cases?

2022-12-16 12:03 UTC, ellykits requested changes

2022-12-16 12:03 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/ResourceExtension.kt
>      this == null -> return ""
This can be reduced to use elvis operator where it is used default to empty string.

```suggestion
//Example
theBase.valueToString() ?: ""
```

2023-02-23 19:06 UTC, pld commented
@maimoonak should we close this in favor of https://github.com/opensrp/fhircore/pull/2046?

2023-02-28 06:41 UTC, f-odhiambo commented
This PR will be closed in favour of #1854

2023-03-01 00:51 UTC, closed without merging