fixed rules for task on household_profile_config
opensrp/fhircore pull request #1863
Opened 2022-11-25 06:30 UTC by aurangzaibumer

Fixes #[https://github.com/opensrp/fhir-resources/issues/464] 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-11-25 09:14 UTC, ellykits requested changes

2022-11-25 09:14 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt
>    }
This function is not generic. I think we can address this use case with JEXL expression. It's possible to loop through a list using JEXL

2022-11-25 09:18 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt
>    }
[JEXL Syntax](https://commons.apache.org/proper/commons-jexl/reference/syntax.html)

2023-01-12 08:30 UTC, aurangzaibumer commented
this can be closed as alternative PRs were merged
https://github.com/opensrp/fhircore/pull/1893
https://github.com/opensrp/fhircore/pull/1899

2023-01-12 08:30 UTC, closed without merging