Update sync flow
opensrp/fhircore pull request #1869
Opened 2022-12-01 05:53 UTC by qaziabubakar-vd

Update sdk dependency

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[https://github.com/opensrp/fhircore/issues/1864] 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-12-07 08:54 UTC, ellykits requested changes

2022-12-07 08:54 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/di/CoreModule.kt
> +  fun provideSyncJob(@ApplicationContext context: Context) = Sync.oneTimeSync<FhirSyncWorker>(context)
Can we use the subclass extending the `FhirSyncWorker` instead?

2022-12-07 08:54 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/di/CoreModule.kt
> +  fun provideSyncJob(@ApplicationContext context: Context) = Sync.oneTimeSync<FhirSyncWorker>(context)
Should be this one [`AppSyncWorker`](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/sync/AppSyncWorker.kt)

2022-12-07 08:54 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/sync/SyncBroadcaster.kt
> +  /*fun runSync() {
Delete commented code/add relevant TODO comment.

2022-12-07 08:54 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt
> +  private val _pollState = MutableSharedFlow<SyncJobStatus>()
```suggestion
  private val _syncPollState = MutableSharedFlow<SyncJobStatus>()
```

2022-12-07 08:54 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt
> +  val pollState: Flow<SyncJobStatus>
```suggestion
  val syncPollState: Flow<SyncJobStatus>
```

2022-12-07 08:54 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/sync/OnSyncListener.kt
>  }
Do we still need this interface?

2022-12-09 11:33 UTC, ndegwamartin commented on android/engine/build.gradle
>          exclude group: 'com.google.android.fhir', module: 'common'
Does the branch break if you add the new SDC artefact as well?

2022-12-13 13:21 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/sync/OnSyncListener.kt
>  }
I think we still do as per our discussion. Revert the `SyncBroadcaster` code.

2022-12-15 12:37 UTC, ellykits commented
Merging this to resolve issues with sync causing app crashes on stage.

2022-12-15 12:38 UTC, merged