Format task due date
opensrp/fhircore pull request #1919
Opened 2022-12-21 11:52 UTC by DebbieArita

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[issue number] 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-12-21 19:13 UTC, dubdabasoduba approved these changes

2022-12-21 19:15 UTC, dubdabasoduba requested changes
Please fix the breaking checker

2022-12-23 12:17 UTC, dubdabasoduba requested changes

2023-01-09 14:56 UTC, ellykits approved these changes

2023-01-09 14:56 UTC, DebbieArita commented on android/engine/src/test/java/org/smartregister/fhircore/engine/rulesengine/RulesFactoryTest.kt
> +
There are existing test cases for this.

2023-01-09 14:57 UTC, merged