Trigger the FhirTaskPlanWorker every time tasks are generated
opensrp/fhircore pull request #1925
Opened 2022-12-27 17:13 UTC by owais-vd

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1909 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-12-27 19:47 UTC, pld requested changes
See https://github.com/opensrp/fhircore/issues/1909#issuecomment-1366134056 for why this must be run periodically

2022-12-28 16:52 UTC, pld submitted a review, later dismissed

2023-01-06 17:13 UTC, pld commented
lgtm! will merge on passing

2023-01-11 11:27 UTC, ellykits commented
Resolve merge conflicts and failing tests @owais-vd  so we can merge this.

2023-01-11 15:12 UTC, pld approved these changes

2023-01-11 15:12 UTC, merged