move test files to standard location
opensrp/fhircore pull request #193
Opened 2021-06-02 14:47 UTC by ndegwamartin

**Type**
Choose one: Code health

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2021-06-04 17:57 UTC, pld submitted a review, later dismissed

2021-06-09 08:44 UTC, ekigamba requested changes

2021-06-09 08:44 UTC, ekigamba commented on android/app/src/test/java/org/smartregister/fhircore/util/UtilsTest.kt
> +@Config(shadows = [FhirApplicationShadow::class])
We probably don't need this since this test does not use Robolectric/Junit4 Runner

2021-06-09 09:44 UTC, ekigamba approved these changes

2021-06-09 09:53 UTC, merged