Add tests for uncovered RulesFactory sections
opensrp/fhircore pull request #1947
Opened 2023-01-11 13:57 UTC by SebaMutuku

* Add tests for function extractAge
* Add tests for functions prettyifyAge

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[issue number] 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2023-01-12 08:12 UTC, ellykits approved these changes

2023-01-13 16:53 UTC, pld approved these changes

2023-01-13 20:36 UTC, pld requested changes

2023-01-13 20:36 UTC, pld commented on android/engine/src/test/java/org/smartregister/fhircore/engine/rulesengine/RulesFactoryTest.kt
> +    Assert.assertEquals("2 days ago", expected)
you can probably imagine why this won't work :D

2023-01-13 20:54 UTC, pld approved these changes

2023-01-13 20:54 UTC, pld commented on android/engine/src/test/java/org/smartregister/fhircore/engine/rulesengine/RulesFactoryTest.kt
> +    val inputDateString = LocalDate.now().minusDays(daysAgo - 1).toString()
I'm kinda confused by why the minus 1 is necessary, I guess if you think of from the end of today? But that feels not intuitive to a user, or maybe there's some more flakiness here that I'm not seeing

2023-01-13 21:40 UTC, merged