Gender input to radio selection, Adjust style client info page
opensrp/fhircore pull request #199
Opened 2021-06-04 09:33 UTC by shoaibmushtaq25

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #183 

**Type**
Choose one: Feature 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2021-06-10 08:49 UTC, shoaibmushtaq25 commented
Screenshot of styling changes , also gender radio buttons
![Screenshot_20210610-134832_FHIR Engine Example](https://user-images.githubusercontent.com/12672919/121494982-a7d5b000-c9f2-11eb-94da-0185fe7295d4.jpg)

2021-06-10 13:00 UTC, ekigamba requested changes

2021-06-10 14:55 UTC, shoaibmushtaq25 commented on android/app/src/main/res/values/styles.xml
> -        <item name="questionnaire_theme">@style/Theme.MaterialComponents.Light.DarkActionBar</item>
Okay. Got it...I can revert this change but Let me explain my problem. We need to show top Title "Client info" as bold, so die to overriding of questionnaire theme, this top Title was not appearing as bold. Please suggest me the alternative to solve my problem? @ekigamba

2021-06-10 14:58 UTC, shoaibmushtaq25 commented on android/app/src/main/res/drawable/rounded_white_bg.xml
> +    <corners android:radius="4dp" />
For the drawable, I checked figma designs, there are different values of corner radius of different screens, i.e, 3 px, 6 px and 10 px. And we made it 10 px bit it looks off (corner radius too bigger). So I changed it to 4dp to make it consistant.. what do you think about it? @ekigamba

2021-06-10 15:04 UTC, shoaibmushtaq25 commented on android/app/src/main/res/layout/activity_questionnaire.xml
> +        android:text="Save"
Yeah sure.

2021-06-10 15:11 UTC, ekigamba commented on android/app/src/main/res/values/styles.xml
> -        <item name="questionnaire_theme">@style/Theme.MaterialComponents.Light.DarkActionBar</item>
Cool, kindly define a style that extends the theme above with the `groupHeaderTextAppearance` as in this file https://github.com/google/android-fhir/blob/master/datacapture/src/main/res/values/styles.xml#L36

2021-06-10 17:56 UTC, ekigamba commented on android/app/src/main/res/drawable/rounded_white_bg.xml
> +    <corners android:radius="4dp" />
Cool this is OK

2021-06-11 07:20 UTC, shoaibmushtaq25 commented on android/app/src/main/res/values/styles.xml
> -        <item name="questionnaire_theme">@style/Theme.MaterialComponents.Light.DarkActionBar</item>
Thanks @ekigamba , I fixed it.

2021-06-11 07:21 UTC, shoaibmushtaq25 commented on android/app/src/main/res/layout/activity_questionnaire.xml
> +        android:text="Save"
Fixed.

2021-06-11 11:23 UTC, ndegwamartin submitted a review, later dismissed

2021-06-11 12:32 UTC, shoaibmushtaq25 commented
Latest screenshot after style change.
![Screenshot_20210611-173150_FHIR Engine Example](https://user-images.githubusercontent.com/12672919/121686716-fbbbc400-cada-11eb-98b0-0def8c753c4b.jpg)

2021-06-11 13:21 UTC, ndegwamartin approved these changes

2021-06-11 13:32 UTC, merged