1996, fix crash indexOutOfBound check with qrItems.size
opensrp/fhircore pull request #1998
Opened 2023-02-02 08:55 UTC by AbdulWahabMemon

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[1996] 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2023-02-03 10:53 UTC, FikriMilano requested changes
Could you add a test case that will fail without this change?

2023-02-07 13:07 UTC, ellykits approved these changes

2023-02-07 13:20 UTC, AbdulWahabMemon commented
> Could you add a test case that will fail without this change?

@FikriMilano , unit test added, can you re review or dismiss your review, so this PR can be able to merge

2023-02-07 14:24 UTC, FikriMilano approved these changes

2023-02-07 18:07 UTC, merged