0.1.9 rc with p2p changes
opensrp/fhircore pull request #2062
Opened 2023-02-20 15:15 UTC by ekigamba

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[issue number] 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2023-03-08 01:29 UTC, dubdabasoduba submitted a review, later dismissed

2023-03-08 14:24 UTC, pld requested changes

2023-03-08 14:24 UTC, pld commented on android/engine/src/main/java/org/smartregister/fhircore/engine/p2p/dao/BaseP2PTransferDao.kt
> +
can we remove all these lines?

2023-03-08 14:24 UTC, pld commented on android/engine/src/test/java/org/smartregister/fhircore/engine/p2p/dao/BaseP2PTransferDaoTest.kt
> +    assertEquals(ParamPrefixEnum.GREATERTHAN_OR_EQUALS, tokenFilters[0].prefix)*/
I think we should delete, put this in an issue

2023-03-08 14:24 UTC, pld commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainActivity.kt
> +        Timber.e(ex)
let's add a test that throws this

2023-03-09 11:23 UTC, Rkareko commented on android/engine/src/main/java/org/smartregister/fhircore/engine/p2p/dao/BaseP2PTransferDao.kt
> +
Yes. Updated

2023-03-09 14:38 UTC, pld approved these changes

2023-03-09 14:38 UTC, merged