1003 add the immunization prerequisite definition and expiry timings
opensrp/fhircore pull request #2222
Opened 2023-04-01 23:16 UTC by ahsanbhatti49

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[issue number] or Closes #[issue number]

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2023-04-01 23:18 UTC, ahsanbhatti49 commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +                subject -> evaluate(questionnaireResponse, questionnaireResponse.descendants().where(linkId='123456').answer.valueString) as taskId then{
@dubdabasoduba  I am not able to evaluate questionnaireResponse Can you please check this?

2023-04-03 15:09 UTC, dubdabasoduba requested changes

2023-04-03 15:09 UTC, dubdabasoduba commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +                subject -> evaluate(questionnaireResponse, $this.descendants().where(linkId='123456').answer.value.toString()) as taskId then{
I don't think this will work because by the time you are generating the references you do not have any pre-generated tasks.

2023-04-04 10:53 UTC, maimoonak requested changes

2023-04-04 10:53 UTC, maimoonak commented on android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
> +  fun `Generate CarePlan should generate child immunization schedule with pre-req def and expiry timing`() =
Where we are making assertion for changes made into this PR like new properties?

2023-04-04 10:53 UTC, maimoonak commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +            //evaluate(src, $this.parameter.where(name='depends-on').resource.entry.where(resource is QuestionnaireResponse).resource) as questionnaireResponse,
why this is commented out?

2023-04-04 10:53 UTC, maimoonak commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +    // fill task into careplan contained and add reference in activity.outcome task.execution.start = task.restriction.start
the statement is commented out which means it would not work

2023-04-04 10:53 UTC, maimoonak commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +                     subject -> input.value = 28 "r_input_value";
it can not be hardcoded. Not every vaccine has same gap

2023-04-04 10:53 UTC, maimoonak commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +          subject -> task.input = create('Task_Input') as input then{
why adding two values for input?

2023-04-05 10:44 UTC, ahsanbhatti49 commented
Linked to this issue 
https://github.com/opensrp/fhir-resources/issues/1003

2023-04-05 13:32 UTC, pld reviewed
if we've confirmed the approach in `TransformSupportServices.kt`can we add tests for the `Task_Input` and `Task_Restriction` types?

2023-04-10 13:40 UTC, pld submitted a review, later dismissed
this looks pretty reasonable to me, can you respond to @maimoonak's comments? I can't tell if those have been addressed

2023-04-10 13:40 UTC, pld commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +        //partof
```suggestion

        // partof
```

2023-04-10 13:40 UTC, pld commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +        subject -> evaluate(subject, $this.birthDate) as patientBirthDate then{
```suggestion
        subject -> evaluate(subject, $this.birthDate) as patientBirthDate then {
```

2023-04-10 13:40 UTC, pld commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +                             subject-> concept.coding = c("http://snomed.info/sct","371154000") as coding then{
```suggestion
         subject -> task.input = create('Task_Input') as input then {
                     subject -> input.type = create("CodeableConcept") as concept then {
                             subject-> concept.coding = c("http://snomed.info/sct","371154000") as coding then {
```

2023-04-10 13:40 UTC, pld commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +        }"r_birth_date";
```suggestion
                                            } "r_evaluated_birth_date";
                                } "r_task_restriction_period";
                        } "r_task_restriction";
        } "r_birth_date";
```

2023-04-10 13:40 UTC, pld commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +                     }"r_codeable_concept";
```suggestion
                     } "r_codeable_concept";
```

2023-04-10 13:40 UTC, pld commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +         }"r_task_input";
```suggestion
         } "r_task_input";
```

2023-04-10 13:40 UTC, pld commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +          }"r_task_input";
```suggestion
                              } "r_codeable_concept";
                              subject -> input.value = taskId "r_input_value";
          } "r_task_input";
```

2023-04-10 13:40 UTC, pld commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +
```suggestion
```

2023-04-10 13:40 UTC, pld commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireActivity.kt
> +
do we need this?

2023-04-14 12:14 UTC, pld commented on android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
> +            //            )
please remove of uncomment

2023-04-14 12:14 UTC, pld commented on android/engine/src/test/resources/plans/child-immunization-schedule/sample/questionnaire-response-register-temp.json
> +
```suggestion
```

2023-04-14 12:14 UTC, pld commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
general cleanup needed, like removing extra lines and commented lines

2023-04-14 16:28 UTC, dubdabasoduba requested changes

2023-04-14 16:28 UTC, dubdabasoduba commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +                              subject -> ref.reference = evaluate(careplan,$this.contained.where(input.last().value =preReqDosage).first().id) "r_task_ref_id";
@ahsanbhatti49 I think the `partOf` attribute should be added for the dependent tasks of the same dosage.

2023-04-14 16:28 UTC, dubdabasoduba commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +                              subject -> ref.reference = evaluate(careplan,$this.contained.where(input.last().value =preReqDosage).first().id) "r_task_ref_id";
This piece of code just add the initially created task as the `partOf`

2023-04-19 17:26 UTC, dubdabasoduba submitted a review, later dismissed

2023-04-19 17:26 UTC, dubdabasoduba commented on android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
> +  }
@ahsanbhatti49 I run this test and I still don't think we are doing the `partOf` addition correctly.  If you look at these dosages https://github.com/opensrp/fhircore/blob/c6a8b273ebfb2e22b32ad1b4cfdab302c674735f/android/engine/src/test/resources/plans/child-immunization-schedule/plandefinition.json#L179-L228 **Sequence 1** depends on **Sequence 0**. So the Tasks representing **Sequence 1** should have a `partOf` reference to the Tasks representing **Sequence 0**

The tasks representing sequence 0 should not have the `partOf` of timing restriction added.

2023-04-27 09:16 UTC, ahsanbhatti49 commented
@dubdabasoduba  If you observe the result of this test, you will see that all the first dosages like OPV 0 does not have the partof property. I have also tagged you on the line where we are fetching the id of previous dosage if it exists.

2023-04-27 09:39 UTC, dubdabasoduba commented
> @dubdabasoduba If you observe the result of this test, you will see that all the first dosages like OPV 0 does not have the partof property. I have also tagged you on the line where we are fetching the id of previous dosage if it exists.

@ahsanbhatti49 I run the test and checked the results. 
```json
{"resourceType":"Task","id":"4152073c-a180-4e49-8f92-0b5ad5b4228b","identifier":[{"use":"official","value":"57066bb3-299c-422d-9da1-a026beb845f3"}],"basedOn":[{"reference":"CarePlan/685ff015-2841-4525-bdef-c1212bd3e8a5"}],"groupIdentifier":{"use":"secondary","value":"0_d"},"partOf":[{"reference":"4152073c-a180-4e49-8f92-0b5ad5b4228b"}],"status":"requested","intent":"plan","priority":"routine","code":{"coding":[{"system":"http://snomed.info/sct","code":"33879002","display":"Administration of vaccine to produce active immunity (procedure)"}]},"description":"BCG  at 0 d vaccine","for":{"reference":"Patient/3e3d698a-4edb-48f9-9330-2f1adc0635d1"},"executionPeriod":{"start":"2021-10-01T00:00:00+03:00","end":"2026-09-30T00:00:00+03:00"},"authoredOn":"2023-04-27T12:33:36+03:00","requester":{"reference":"Practitioner/3812"},"owner":{"reference":"Practitioner/3812"},"reasonCode":{"coding":[{"system":"http://snomed.info/sct","code":"42284007","display":"BCG vaccination"}],"text":"BCG"},"reasonReference":{"reference":"Questionnaire/9b1aa23b-577c-4fb2-84e3-591e6facaf82"},"restriction":{"period":{"start":"2021-10-01T00:00:00.00Z","end":"2026-09-30T00:00:00.00Z"}},"input":[{"type":{"coding":[{"system":"http://snomed.info/sct","code":"371154000","display":"Dependent (qualifier value)"}]},"valueInteger":28},{"valueString":"BCG "}]}
```

Attached is the BCG task created. It seems to have a `partOf` reference and a 28 days timing added to it. However, the plandef [here](https://github.com/opensrp/fhircore/blob/37367d15fbe468c30dd3272c30caf9e4f72e04c2/android/engine/src/test/resources/plans/child-immunization-schedule/plandefinition.json#L139-L152) does not define any pre-requisite for that tasks. 

A task should only have a pre-requisite if it's the n+1 in the dosage array.

2023-04-27 11:19 UTC, ahsanbhatti49 commented
> 

@dubdabasoduba  Yes you are right, The dosages which dont have the sequence were not handled properly.
I have updated the PR and managed to handle this.

2023-04-27 12:36 UTC, pld commented
@ahsanbhatti49 can you please add/extend the tests to cover the new lines?

2023-04-27 21:49 UTC, ahsanbhatti49 commented
> @ahsanbhatti49 can you please add/extend the tests to cover the new lines?

@pld   code added in fhircore side is refactored and removed

2023-04-28 12:46 UTC, maimoonak reviewed
Ahsan this looks ok, however, we need to add assertions for new properties we have added. Once added those this looks good to go.

2023-04-28 12:46 UTC, maimoonak commented on android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
> +            assertTrue(tasks.all { it.input.firstOrNull()?.value.valueToString() == "28" })
Also add assertion for input 'sequence' concept with code, system, display, and value

2023-04-28 12:46 UTC, maimoonak commented on android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
> +          .also { tasks ->
also add assertion for code, system, and dispplay for this gap concept

2023-04-28 12:46 UTC, maimoonak commented on android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
> +                it.restriction.period.start.asYyyyMmDd() == patient.birthDate.asYyyyMmDd()
assert restriction period end as well atleast for for few known vaccines like bcg, penta1, 2, 3 to make sure that it works fine for end date assignment..

2023-04-28 12:46 UTC, maimoonak commented on android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
> +              }
assert part of for few known vaccine to ensure the functionality for bcg, penta1,2,3 to check the pre-req assignment.

2023-04-28 14:30 UTC, maimoonak submitted a review, later dismissed

2023-04-28 15:32 UTC, pld commented on android/engine/src/test/resources/plans/child-immunization-schedule/structure-map-register.txt
> +
```suggestion
```

2023-04-28 15:34 UTC, pld approved these changes

2023-04-28 15:54 UTC, pld approved these changes

2023-04-28 18:19 UTC, merged