Minor fix in care plan generation
opensrp/fhircore pull request #2223
Opened 2023-04-03 06:09 UTC by qaziabubakar-vd

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[issue number] or Closes #[issue number]

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2023-04-03 10:10 UTC, maimoonak submitted a review, later dismissed
Kindly add an issue for technical debt and add along with TODO comment in code.

2023-04-03 13:07 UTC, pld requested changes
please a test that fails without this change and passes with it

2023-04-04 16:20 UTC, ellykits approved these changes

2023-04-06 13:44 UTC, ellykits commented
@qaziabubakar Kindly address @pld  comment on test so we can have this merged.

2023-04-06 14:07 UTC, qaziabubakar-vd commented
> @qaziabubakar Kindly address @pld comment on test so we can have this merged.

Working on it, will update the PR with test and share for review

2023-04-08 01:16 UTC, pld submitted a review, later dismissed
🎉

2023-04-08 01:16 UTC, pld commented on android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt
> +                  // Todo handle cases where we explicitly need to set previous value as null, when
```suggestion
                  // TODO handle cases where we explicitly need to set previous value as null, when
```

2023-04-08 01:17 UTC, pld commented on android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
> +  fun `test generateOrUpdateCarePlan returns success even when evaluatedValue is null`() =
```suggestion
  @Test
  @ExperimentalCoroutinesAp
  fun `test generateOrUpdateCarePlan returns success even when evaluatedValue is null`() =
```

2023-04-08 01:17 UTC, pld approved these changes

2023-04-08 01:40 UTC, pld commented on android/engine/src/test/java/org/smartregister/fhircore/engine/task/FhirCarePlanGeneratorTest.kt
> +  fun `test generateOrUpdateCarePlan returns success even when evaluatedValue is null`() =
```suggestion
  @ExperimentalCoroutinesApi
  fun `test generateOrUpdateCarePlan returns success even when evaluatedValue is null`() =
```

2023-04-08 01:40 UTC, pld approved these changes

2023-04-08 02:59 UTC, merged