Fix issue 2274 [ Invalidate cache when retrieving register data and executing filtering with params shared across screens]
opensrp/fhircore pull request #2275
Opened 2023-04-24 10:28 UTC by SebaMutuku

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #2274 

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2023-04-24 14:23 UTC, ellykits requested changes

2023-04-24 14:23 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/RegisterRepository.kt
> +            it.isFilterParam == true
Why do we need this new property? can we have a list of all the param types (instead) that at filterable and confirm if the current `paramType` is in the list.

2023-04-24 14:23 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt
> +    if (configCacheMap.contains(configKey) && paramsMap?.isEmpty() == true)
Please document why the `paramsMap.isEmpty` check is necessary

2023-04-26 16:35 UTC, pld approved these changes

2023-04-26 16:35 UTC, pld commented on android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt
> +   * confirm that actual params used in the dataQuery are passed when retrieving the configurations.
```suggestion
   * you are passing data across screens, then later using it in DataQueries and to retrieve
   * registerConfiguration. It is necessary to check that [paramsMap] is empty to confirm
   * that the params used in the DataQuery are passed when retrieving the configurations.
```

2023-04-26 16:36 UTC, pld approved these changes

2023-04-26 17:58 UTC, pld approved these changes

2023-04-26 17:58 UTC, pld commented on android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/ConfigurationRegistry.kt
> +      return configCacheMap[configKey] as T
this is a know issue, jacoco can't detect coverage on inline functions

2023-04-26 17:59 UTC, merged