Fix sorting related resources
opensrp/fhircore pull request #2439
Opened 2023-06-09 15:20 UTC by ellykits

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Closes #2437 

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2023-06-09 15:28 UTC, dubdabasoduba requested changes

2023-06-09 15:35 UTC, ellykits commented on android/quest/src/main/assets/configs/app/profiles/default_profile_config.json
> +                  }
Okay

2023-06-12 13:18 UTC, pld approved these changes

2023-06-12 13:18 UTC, pld commented on android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/RegisterRepository.kt
> +            /*Unsupported data type*/
do we want to log this?

2023-06-12 13:18 UTC, pld commented on android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt
> +    @JvmOverloads
very interesting! I hadn't heard of this annotation before, https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/-jvm-overloads/

2023-06-13 13:55 UTC, dubdabasoduba approved these changes

2023-06-13 14:00 UTC, merged