Fixed reloading data when change managing entity is sucessfully completes
opensrp/fhircore pull request #2454
Opened 2023-06-14 02:59 UTC by aurangzaibumer

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes - https://github.com/opensrp/fhir-resources/issues/1742

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2023-06-14 03:05 UTC, aurangzaibumer commented on android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesListener.kt
> +        else -> log(exception, "failed to execute rule : ${rule.name} ")
added just to print the rule name when fails

2023-06-14 07:38 UTC, ellykits requested changes

2023-06-14 07:38 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/profile/ProfileViewModel.kt
> +  val shouldReloadData = MutableLiveData<Boolean>()
Why do we need a new LiveData just to refresh the profile when dialog is dismissed?

2023-06-14 07:38 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/profile/ProfileFragment.kt
> +    profileViewModel.shouldReloadData.observe(viewLifecycleOwner) {
Do we need a new live data?

2023-06-14 11:05 UTC, ellykits requested changes

2023-06-14 11:05 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/profile/ProfileFragment.kt
> +
I think we can move the function block (and delete this private function) to where this is called as this private function is only called from one place.

2023-06-14 12:11 UTC, ellykits submitted a review, later dismissed

2023-06-15 01:51 UTC, pld approved these changes

2023-06-15 01:51 UTC, merged