Update other-patients name
opensrp/fhircore pull request #2459
Opened 2023-06-15 08:03 UTC by Lentumunai-Mark

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

[Fixes #[2458]](https://github.com/opensrp/fhircore/issues/2458)

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2023-06-15 08:05 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt
> +          title = event.title
What's the event title here? Is it coming from configuration?

2023-06-15 08:08 UTC, ellykits requested changes

2023-06-15 08:08 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/AppDrawer.kt
> +        title = navigationConfiguration.bottomSheetRegisters?.display!!
This has a potential `NullPointerException` with the `!!` on the `display` property. Make `title` nullable instead. Then apply an if condition for when `title.isNullOrEmpty()` - use default `Other patients` string.

2023-06-15 09:50 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt
> +              "Other patients"
Extract hard-coded string to `string.xml` resource file

2023-06-15 09:50 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/AppDrawer.kt
> +            "Other Patients"
Extract hard-coded string to `string.xml` resource file

2023-06-16 13:22 UTC, pld commented on android/engine/src/androidTest/java/org/smartregister/fhircore/engine/ui/bottomsheet/RegisterBottomSheetFragmentViewKtTest.kt
please remove Kt from name

2023-06-16 15:05 UTC, ellykits approved these changes

2023-06-19 09:13 UTC, ellykits approved these changes

2023-06-19 15:00 UTC, merged