Add the Practitioner selection screen on the In-app reporting workflow
opensrp/fhircore pull request #2605
Opened 2023-07-20 05:03 UTC by Rkareko

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #2472 

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2023-07-20 13:07 UTC, ellykits requested changes

2023-07-20 13:07 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/util/extensions/ConfigExtensions.kt
> +        val interpolatedParams = interpolateActionParamsValue(actionConfig, resourceData)
Can this interpolation be done before the `when` clause so all branches can benefit from it?

2023-07-20 17:24 UTC, pld commented on android/quest/src/test/java/org/smartregister/fhircore/quest/util/extensions/ConfigExtensionsTest.kt
> +    Assert.assertEquals("practitioner_id", slotBundle.captured.getString(NavigationArg.RESOURCE_ID))
this assert is returning null

2023-07-21 07:38 UTC, Rkareko commented on android/quest/src/test/java/org/smartregister/fhircore/quest/util/extensions/ConfigExtensionsTest.kt
> +    Assert.assertEquals("practitioner_id", slotBundle.captured.getString(NavigationArg.RESOURCE_ID))
This has been fixed

2023-07-21 07:38 UTC, ellykits submitted a review, later dismissed
:+1: LGTM

2023-07-21 13:25 UTC, pld approved these changes

2023-07-21 13:25 UTC, merged