Fix APK crash for app built on Main branch
opensrp/fhircore pull request #2658
Opened 2023-08-08 16:07 UTC by ndegwamartin

- Running an app built from main crashes the app after entering App ID

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #2651 

**Engineer Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [x] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2023-08-08 16:42 UTC, ellykits requested changes

2023-08-08 16:42 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/appsetting/AppSettingViewModel.kt
> +  @VisibleForTesting fun isNonProxy(): Boolean = _isNonProxy
Is this annotation necessary? The function can be accessed regardless.

2023-08-08 16:50 UTC, ndegwamartin commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/appsetting/AppSettingViewModel.kt
> +                    "",
Good catch 👍🏾

2023-08-09 00:59 UTC, pld approved these changes

2023-08-09 07:56 UTC, ellykits approved these changes

2023-08-09 07:57 UTC, merged