[DNM] WIP build files for oob building in android studio
OpenSRP/fhircore pull request #27
Opened 2021-03-07 16:18 UTC by pld

Possibly everything in this PR is bad, feel free to junk it all, I'm an Android newbie :)

This does NOT work as is, fail with an error about `sdk_version` in the `android` gradle file being undefined.

Goal is to get something that builds in Android Studio with no changes immediately on checkout.

2021-03-07 16:19 UTC, pld commented
@Andati @rkodev see notes above, my limited Android skills on display here :)

If you could take this up (or just ignore it, very aware nothing here might be useful), goal is to be able to run a build without any changes in Android Studio in checkout

2021-03-08 08:47 UTC, rkodev requested changes
@pld We need to exclude all the files in the .idea and .gradle folder in the PR as well.

2021-03-08 12:31 UTC, pld commented
Cool, please go ahead and make changes to the PR

2021-03-08 12:49 UTC, rkodev approved these changes

2021-03-08 14:01 UTC, Andati approved these changes

2021-03-08 14:14 UTC, merged