[Quest/Malawi Core] Filter guardian task using the meta tag
opensrp/fhircore pull request #2725
Opened 2023-09-04 14:30 UTC by calmwalija

## Description
Filter guardian task using the meta tag

**Additional context**
There has been an addition to the Binary/app-config-saa-prod
```
{
  "taskFilterTagViaMetaCodingSystem": "https://d-tree.org/fhir/task-filter-tag"
}
```

For guardian visits, the meta tag looks like  below

```
  {
    "system": "https://d-tree.org/fhir/task-filter-tag",
    "code": "guardian-visit"
  }
```

2023-09-05 18:24 UTC, evance-mose submitted a review, later dismissed

2023-09-05 18:43 UTC, sevenreup requested changes

2023-09-05 18:43 UTC, sevenreup commented on android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/app/ApplicationConfiguration.kt
> +  var taskFilterTagViaMetaCodingSystem: String = ""
Make the default the current tag. You can add it as a constant in ConfigurationRegistry.

2023-09-06 11:27 UTC, sevenreup approved these changes

2023-09-06 11:29 UTC, merged