[ZEIR] - Growth Monitoring : Z-Score Computation
opensrp/fhircore pull request #2745
Opened 2023-09-12 10:50 UTC by qaziabubakar-vd

Linked Issue: https://github.com/onaio/fhir-resources/issues/1535

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes [link to issue]

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2023-09-12 12:32 UTC, f-odhiambo approved these changes
LGTM

2023-09-13 07:51 UTC, pld requested changes

2023-09-13 09:53 UTC, ellykits requested changes

2023-09-13 09:53 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
> +          withContext(Dispatchers.IO) {
Can you use `dispatcherProvider.io()` here instead? The provider is already injected as a constructor parameter

2023-09-13 10:06 UTC, pld approved these changes

2023-09-14 08:00 UTC, merged