1399 order of household register
opensrp/fhircore pull request #2855
Opened 2023-11-10 09:02 UTC by AbdulWahabMemon

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #https://github.com/onaio/fhir-resources/issues/1399

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2023-11-16 12:14 UTC, ageryck submitted a review, later dismissed

2023-11-16 13:07 UTC, ageryck commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
> +    defaultRepository.addOrUpdate(resource = group)
The group resource is a base resource on the register/profile, we want to indicate it as updated as long as related resources are. The pros to this it allows us to filter the group with the latest interaction to the register top but the con is that we will interfere with the audit trail of group resource-specific edits

2023-11-16 13:33 UTC, dubdabasoduba commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
> +    defaultRepository.addOrUpdate(resource = group)
@ageryck I think the above use case is already handled by configs. @SebaMutuku worked on something that allowed us to define the group to update once a resource tied to the group is altered

2023-11-16 13:35 UTC, dubdabasoduba commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
> +    defaultRepository.addOrUpdate(resource = group)
@AbdulWahabMemon In the cases where the group is not updated to we have it defined on the questionnaire configs that open the forms that create the said resources

2023-11-16 13:48 UTC, Rkareko approved these changes

2023-11-16 13:49 UTC, dubdabasoduba commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
> +    defaultRepository.addOrUpdate(resource = group)
NVM my question above I checked the code. The change makes sense

2023-11-16 13:50 UTC, Rkareko commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
> +    defaultRepository.addOrUpdate(resource = group)
@ageryck @AbdulWahabMemon Could you add a short comment on the code that explains the need for the change

2023-11-16 14:07 UTC, AbdulWahabMemon commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
> +    defaultRepository.addOrUpdate(resource = group)
> @AbdulWahabMemon In the cases where the group is not updated to we have it defined on the questionnaire configs that open the forms that create the said resources?

for every questionnaire with groupIdentifier, group is updated with _lastUpdated but only store in db when passing the check at line 662 in QuestionnaireViewModel, 
that fails to sorting group in register if there is interaction inside group like Tasks, Encounter, Observations, are created/updated for a group, these ResourceType check is not at that line, so either we can add those ResourceType check or we can update group outside that check.

2023-11-16 19:38 UTC, AbdulWahabMemon commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
> +    defaultRepository.addOrUpdate(resource = group)
@Rkareko comment added

2023-11-17 07:27 UTC, ageryck submitted a review, later dismissed

2023-11-17 08:14 UTC, dubdabasoduba requested changes

2023-11-17 08:14 UTC, dubdabasoduba commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt
> +    // so for every cases group is to be updated
```suggestion
    // here Group is coming with groupIdentifier thus it make sense that
    // there is an interaction inside group rather addingMemberItems only for above check
    // so for every cases group is to be updated
    
    /**
    * The Group Resource is fetched by the `groupIdentifier`.  
    * We trigger the group update every time anything linked to it in order to change the `_lastUpdated` timestamp.
    * This helps us with order the last updated group (household) on the top of the register. 
    */
```

2023-11-17 12:08 UTC, dubdabasoduba approved these changes

2023-11-17 13:45 UTC, dubdabasoduba approved these changes

2023-11-17 13:45 UTC, merged