Fix not picking completed careplan
opensrp/fhircore pull request #2878
Opened 2023-11-21 17:50 UTC by aurangzaibumer

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes [link to issue]

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2023-11-28 16:25 UTC, dubdabasoduba requested changes

2023-11-28 16:25 UTC, dubdabasoduba commented on android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt
> +            { value = of(CarePlanStatus.ENTEREDINERROR.toCode()) },
@aurangzaibumer I think we can remove this. By the time the CarePlan us marked as entered in error it means the it should be closed

2023-12-19 10:07 UTC, ellykits commented
@aurangzaibumer Do we need this PR for the main branch? @dubdabasoduba Can you review this?

2023-12-19 10:29 UTC, aurangzaibumer commented
> @aurangzaibumer Do we need this PR for the main branch? @dubdabasoduba Can you review this?

Yes, we do need this PR because app was picking a completed careplan which was a bug. Here's PR to the main https://github.com/opensrp/fhircore/pull/2929

2023-12-19 10:35 UTC, ellykits commented
> > @aurangzaibumer Do we need this PR for the main branch? @dubdabasoduba Can you review this?
> 
> Yes, we do need this PR because app was picking a completed careplan which was a bug. Here's PR to the main #2929

Thanks. Kindly create a corresponding PR pointing to `main` branch.

2023-12-21 09:08 UTC, aurangzaibumer commented
> > > @aurangzaibumer Do we need this PR for the main branch? @dubdabasoduba Can you review this?
> > 
> > 
> > Yes, we do need this PR because app was picking a completed careplan which was a bug. Here's PR to the main #2929
> 
> Thanks. Kindly create a corresponding PR pointing to `main` branch.

done. should we merge this PR now? or this needs to be closed?

2023-12-21 11:38 UTC, dubdabasoduba approved these changes

2023-12-21 11:49 UTC, merged