Implement configurable data migration using SDK search API
opensrp/fhircore pull request #2927
Opened 2023-12-18 16:24 UTC by ellykits

Example use case: Fix an issue with extraction for instance this can be used to fix incorreclty extract reference. Configuration accepts data queries and resource type to search then applies the update values on the resources. This function should be blocking and should run immediately after login.

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes [link to issue]

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2023-12-18 16:26 UTC, ellykits commented
@dubdabasoduba I have drafted this PR for your review on how the supposed configurable data migration should work. I updated the value section to use a `RuleConfig` instead for more flexibility. This should allow us to populate the rules facts with more data if needed. I noted this functionality may consume a lot of resources because of the DB reads & writes thus it should only be run once and versioned to prevent unnecessary migration.

2023-12-20 12:00 UTC, dubdabasoduba requested changes

2023-12-20 12:07 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/datastore/PreferenceDataStore.kt
> +    val MIGRATION_VERSION by lazy { intPreferencesKey("migrationVersion") }
We can't use `const` keywords on delegated properties. The variables are declared in the `companion object` of the class; thus they are always static and declared only once. The `strings` are only useful in that context and are not used anywhere else in the application. This improves readability.

2023-12-20 12:08 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/data/DataMigration.kt
> +          }
I will add the documentation. Queries used in this contexts are not related to base/related resources but rather any kind of resource stored in the database.

2023-12-20 12:13 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/data/DataMigration.kt
> +    val maxVersion = migrationConfigs?.maxOfOrNull { it.version } ?: previousVersion
By the time we reach this line of code, we are certain there are new migrations. Before this function is called we retrieve new migrations via 

```kotlin 
val previousVersion = preferenceDataStore.read(PreferenceDataStore.MIGRATION_VERSION).first()
val newMigrations = migrations?.filter { it.version > previousVersion }
```

The maximum version is derived from the list of the `newMigrations`

2023-12-20 15:04 UTC, ellykits commented
Pushing the UI updates in a few...

2023-12-22 15:31 UTC, merged