Fix add group member and change group resource managing entity
opensrp/fhircore pull request #3030
Opened 2024-02-01 10:04 UTC by ellykits

Add group member should run after the generated member resources have been created and saved to the DB.

Change managing entity should use the same code to identify the RelatedPerson object.

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes [link to issue]

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2024-02-01 12:07 UTC, dubdabasoduba requested changes

2024-02-01 13:01 UTC, pld commented on android/engine/src/main/java/org/smartregister/fhircore/engine/sync/AppSyncWorker.kt
> +    UploadConfiguration(useETagForUpload = false, uploadBundleSize = 100)
oh, I missed this was going into 025, for this branch, I'd say leave as is, do not refactor to hard-coded config, but if we want this change in main, refactor at that point

2024-02-01 13:16 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/sync/AppSyncWorker.kt
> +    UploadConfiguration(useETagForUpload = false, uploadBundleSize = 100)
Oh I missed that. That was included while were were debugging the sync issue. My bad.

2024-02-01 13:17 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/sync/AppSyncWorker.kt
> +    UploadConfiguration(useETagForUpload = false, uploadBundleSize = 100)
I will revert.

2024-02-01 13:22 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/sync/AppSyncWorker.kt
> +    UploadConfiguration(useETagForUpload = false, uploadBundleSize = 100)
@pld Just to let you know the fixes on this PR are already merged in `main` branch.

2024-02-01 18:35 UTC, dubdabasoduba approved these changes

2024-02-05 13:05 UTC, ageryck approved these changes

2024-02-05 13:05 UTC, merged