Test change manging entity opens bottomsheet
opensrp/fhircore pull request #3031
Opened 2024-02-01 13:58 UTC by SebaMutuku

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

CHT

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2024-02-06 10:09 UTC, ellykits requested changes

2024-02-06 10:09 UTC, ellykits commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/profile/ProfileViewModelTest.kt
> +  fun testManagingEntityShowsProfileBottomSheetFragment() = runTest {
Rename test case to indicate what is actually being tested, what should be the expected behaviour?

E.g. `testThatManagingEntityProfileBottomSheetIsShownOnActionTriggered`

2024-02-06 10:09 UTC, ellykits commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/profile/ProfileViewModelTest.kt
> +    every { fhirPathDataExtractor.extractValue(managingEntityResource, any()) } returns "true"
Is it possible to avoid using mocks here? `fhirPathDataExtractor` is simply a utility class.

2024-02-06 19:21 UTC, pld approved these changes

2024-02-27 11:34 UTC, Rkareko approved these changes

2024-02-27 11:38 UTC, merged