Add location service to calculate distance between two locations.
opensrp/fhircore pull request #3074
Opened 2024-02-16 06:39 UTC by Lentumunai-Mark

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes [link to issue]

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2024-02-20 16:49 UTC, pld requested changes

2024-02-20 16:49 UTC, pld commented on android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/services/LocationService.kt
> +      val distanceInKilometers = distanceInMeters / 1000.0
move number to a constant like `METERS_IN_A_KILOMETER`

2024-02-20 18:01 UTC, dubdabasoduba requested changes

2024-02-20 18:01 UTC, dubdabasoduba commented on android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/services/LocationService.kt
> +  private fun formatDistance(distanceInMeters: Float): String {
@Lentumunai-Mark this is not important for this ticket but create another ticket to allow us to convert the Kilometers to miles if we even need it

2024-02-22 17:27 UTC, pld submitted a review, later dismissed

2024-02-27 06:44 UTC, Lentumunai-Mark commented
Closing this in favor of #3107

2024-02-27 06:44 UTC, closed without merging