Add OpenSRP2 Web documentation to docusite
opensrp/fhircore pull request #3084
Opened 2024-02-20 14:26 UTC by owais-vd

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #3082 

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2024-02-25 14:23 UTC, dubdabasoduba requested changes
@rowo @pld Can we have the following sections on the documentation
1. The features pages: - Shows the features the on OpenSRP web
2. The user guide pages: - Shows a guide on how to use OpenSRP web

2024-02-26 14:37 UTC, pld commented
is what's in this PR the features? Is the user guide still on the confluent wiki?

2024-02-26 19:12 UTC, pld approved these changes

2024-02-26 19:12 UTC, pld commented
I will merge this for now, we can add more later

2024-02-26 19:12 UTC, merged