Write Unit Tests on Related Entity Location sync strategy enchancements
opensrp/fhircore pull request #3144
Opened 2024-03-15 07:17 UTC by brandy-kay

…urce identifier**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes 3105

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2024-03-19 12:15 UTC, ellykits requested changes

2024-03-19 12:15 UTC, ellykits commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
> +    assertEquals(subjectType, questionnaireConfig.resourceType)
These assertions will always be evaluated to be true. The assertions are not done against the meta tags as the name of the test suggests.

2024-03-19 12:15 UTC, ellykits commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
> +    val bundle = bundleSlot.captured
The slot is captured here when there is no function called with the bundle as a parameter.

2024-03-19 12:15 UTC, ellykits commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
> +    }
The assertions here are not done against the metatags as the name of the test suggests.

2024-03-19 12:15 UTC, ellykits commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
> +  fun `test saveExtractedResources for resource modification`() = runBlocking {
What are we testing here?

2024-03-19 12:15 UTC, ellykits commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
> +    assertEquals("patientLogicalId", questionnaireResponse.subject.reference)
Can you add more assertions/verifications for this test?

2024-03-19 12:16 UTC, ellykits commented
Use the same naming convention for the test cases. See the documentation on [OpenSRP docs](https://docs.opensrp.io/engineering/android-app/developer-setup/testing/unit-tests)

2024-03-19 12:33 UTC, ellykits commented
@brandy-kay The tests should be re-written to verify and assert that related entity location meta tag is indeed added to the extracted resources from a questionnaire submission. To achieve this, the questionnaire needs to include a field that will be used to capture the location uuid. The link Id of this field is required to be configured in the Questionnaire Config. Refer to the code changes made in the [PR 3097](https://github.com/opensrp/fhircore/pull/3097) referenced in the issue.

2024-04-15 13:54 UTC, ellykits requested changes

2024-04-15 13:54 UTC, ellykits commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
> +    assertEquals(listResource.id, linkId)
Can you assert that the Related Entity Location resource meta tag was added to the resource meat property?

2024-04-16 13:04 UTC, brandy-kay commented
@ellykits  have added assertion for the related entity resource meta tag

2024-04-18 11:39 UTC, ndegwamartin commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
> +  fun isRelatedEntityLocationMetaTagAddedToExtractedResource() = runBlocking {
Rename this test case to align with the others. Maybe something like
```suggestion
  fun testSaveExtractedResourcesAddsRelatedEntityLocationMetaTagToExtractedResource() = runBlocking {
```

2024-04-18 11:43 UTC, ndegwamartin commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
> +    if (resource != null) {
Instead of this condition use `assertNotNull(`

2024-04-18 11:50 UTC, ndegwamartin commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
> +            id = UUID.randomUUID().toString()
Use a dummy test uuid so that you can use it in the assert as well (to confirm it is actually the correct one added)

2024-04-18 11:50 UTC, ndegwamartin commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
> +          it.system == "https://smartregister.org/related-entity-location-tag-id"
Assert the REL UUID as well

2024-04-18 14:26 UTC, ndegwamartin commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
> +          it.system == "https://smartregister.org/related-entity-location-tag-id"
The `any( `method of the Iterable interface will always return a Boolean, so this test will always pass regardless of the values checked.

2024-04-18 14:27 UTC, ndegwamartin commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModelTest.kt
> +          it.system == "https://smartregister.org/related-entity-location-tag-id"
In my previous comment for the `assertNotNull` was only to replace the if condition that was there previously

2024-04-19 08:05 UTC, ndegwamartin approved these changes

2024-04-19 09:37 UTC, merged