Update event mangement logic to factor in resource type when closing resources
opensrp/fhircore pull request #3152
Opened 2024-03-18 12:34 UTC by Rkareko

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #3149

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2024-03-18 12:40 UTC, Rkareko commented
Sample of the updated values 
```
      "updateValues": [
        {
          "jsonPathExpression": "Task.status",
          "value": "cancelled",
          "resourceType": "Task"
        },
        {
          "jsonPathExpression": "CarePlan.status",
          "value": "completed",
          "resourceType": "CarePlan"
        },
        {
          "jsonPathExpression": "ServiceRequest.status",
          "value": "revoked",
          "resourceType": "ServiceRequest"
        }
      ],
      "resourceFilterExpressions": [
        {
          "conditionalFhirPathExpressions": "Task.status != 'completed'",
          "resourceType": "Task"
        },
        {
          "conditionalFhirPathExpressions": "ServiceRequest.status != 'completed'",
          "resourceType": "ServiceRequest"
        }
      ]
```

Here is a sample of a complete `eventWorkFlow` config

```
{
  "eventWorkflows": [
    {
      "eventType": "RESOURCE_CLOSURE",
      "triggerConditions": [
        {
          "eventResourceId": "carePlanToBeClosed",
          "conditionalFhirPathExpressions": [
            "true"
          ]
        },
        {
          "eventResourceId": "referralServiceRequestToBeClosed",
          "conditionalFhirPathExpressions": [
            "%resource.entry.where(resource is QuestionnaireResponse).resource.where(questionnaire = 'Questionnaire/dc-remove-patient').exists() and %resource.entry.where(resource is QuestionnaireResponse).resource.repeat(item).where(linkId = 'reason-for-removal' and (answer.value.code = 'died' or answer.value.code = 'moved-away')).exists()"
          ]
        }
      ],
      "eventResources": [
        {
          "id": "carePlanToBeClosed",
          "resource": "CarePlan",
          "configRules": [
            {
              "name": "patientId",
              "condition": "true",
              "actions": [
                "data.put('patientId', fhirPath.extractValue(Patient, 'Patient.id'))"
              ]
            }
          ],
          "dataQueries": [
            {
              "paramName": "instantiates-canonical",
              "filterCriteria": [
                {
                  "dataType": "REFERENCE",
                  "value": "PlanDefinition/dc-diabetes-screening-intervention"
                }
              ]
            },
            {
              "paramName": "subject",
              "filterCriteria": [
                {
                  "dataType": "REFERENCE",
                  "computedRule": "patientId"
                }
              ]
            }
          ],
          "relatedResources": [
            {
              "resource": "Task",
              "searchParameter": "based-on"
            }
          ]
        },
        {
          "id": "referralServiceRequestToBeClosed",
          "resource": "ServiceRequest",
          "configRules": [
            {
              "name": "patientId",
              "condition": "true",
              "actions": [
                "data.put('patientId', fhirPath.extractValue(Patient, 'Patient.id'))"
              ]
            }
          ],
          "dataQueries": [
            {
              "paramName": "code",
              "filterCriteria": [
                {
                  "dataType": "CODEABLECONCEPT",
                  "value": {
                    "system": "http://snomed.info/sct",
                    "code": "44383000"
                  }
                }
              ]
            },
            {
              "paramName": "subject",
              "filterCriteria": [
                {
                  "dataType": "REFERENCE",
                  "computedRule": "patientId"
                }
              ]
            }
          ]
        }
      ],
      "updateValues": [
        {
          "jsonPathExpression": "Task.status",
          "value": "cancelled",
          "resourceType": "Task"
        },
        {
          "jsonPathExpression": "CarePlan.status",
          "value": "completed",
          "resourceType": "CarePlan"
        },
        {
          "jsonPathExpression": "ServiceRequest.status",
          "value": "revoked",
          "resourceType": "ServiceRequest"
        }
      ],
      "resourceFilterExpressions": [
        {
          "conditionalFhirPathExpressions": "Task.status != 'completed'",
          "resourceType": "Task"
        },
        {
          "conditionalFhirPathExpressions": "ServiceRequest.status != 'completed'",
          "resourceType": "ServiceRequest"
        }
      ]
    }
  ]
}
```

2024-03-19 11:55 UTC, ellykits requested changes

2024-03-19 11:55 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/event/EventWorkflow.kt
> +  val resourceType: String,
```suggestion
  val resourceType: ResourceType,
```

2024-03-19 11:55 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt
> +                updateExpression.jsonPathExpression.replace(resource.resourceType.name, "\$"),
```suggestion
                updateExpression.jsonPathExpression.replace(resource.resourceType.name, "\$", ignoreCase = true),
```

2024-03-19 11:55 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/ResourceFilterExpression.kt
> +  val resourceType: String = "",
```suggestion
  val resourceType: ResourceType,
```

2024-03-19 12:57 UTC, Rkareko commented
App crashes when loading Profile screen. Do not merge till this is fixed.

2024-03-20 07:49 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/event/EventWorkflow.kt
> +  val resourceType: ResourceType = ResourceType.Task,
Is defaulting to `Task` resource necessary?

2024-03-20 07:49 UTC, ellykits reviewed
This LGTM? left a single comment.

2024-03-20 07:52 UTC, ellykits commented
> App crashes when loading Profile screen. Do not merge till this is fixed.

@Rkareko This could be related to the updated configs. The existing configs need to be updated for the rest of the apps using this feature.

2024-03-20 07:55 UTC, ellykits commented
Update the docs, then we can have this merged.

2024-03-20 12:19 UTC, ellykits approved these changes

2024-03-20 14:42 UTC, merged