Docs for P2P Sync
opensrp/fhircore pull request #3192
Opened 2024-04-09 12:12 UTC by SebaMutuku

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2024-04-15 15:53 UTC, pld requested changes

2024-04-15 15:53 UTC, pld commented on docs/engineering/android-app/configuring/p2p_sync.mdx
> +menuIconConfig | The icon to show. This can be configured through ICON configuration. See widgets | No  |  |
Can add the link to the ICON config directly here please?

2024-04-15 15:53 UTC, pld commented on docs/engineering/android-app/configuring/p2p_sync.mdx
> +A WORKFLOW can be launched anywhere on the app through an action. Either by a text link, actionable button, or image icon.
What is the `WORKFLOW` you are referring to here?

2024-05-15 06:06 UTC, ellykits requested changes

2024-05-15 06:06 UTC, ellykits commented on docs/engineering/android-app/configuring/p2p_sync.mdx
> +:::
```suggestion
:::info
DEVICE_TO_DEVICE_SYNC application workflow can be triggered via configurable actions as indicated in the sample navigation configuration above.
:::
```

2024-05-15 06:08 UTC, ellykits approved these changes

2024-05-15 06:08 UTC, merged