QR to HTML Population
opensrp/fhircore pull request #3259
Opened 2024-05-14 09:18 UTC by FikriMilano

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #3257

**Engineer Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [x] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2024-05-20 09:57 UTC, ellykits submitted a review, later dismissed

2024-05-20 15:11 UTC, ndegwamartin commented
This implementation could be refactored for some optimization e.g. use one while loop with if else statements for the various conditions during parsing or using regex for the various parse/replace logic.

The performance gains are probably negligible for the size of HTML we are parsing so will go ahead and approve this. We can keep a look out and perform any refactors accordingly incase latency is noticable.

2024-05-20 15:11 UTC, ndegwamartin commented
cc @FikriMilano

2024-05-20 15:12 UTC, ndegwamartin submitted a review, later dismissed

2024-05-20 15:18 UTC, pld requested changes

2024-05-20 15:18 UTC, pld commented on android/engine/src/main/java/org/smartregister/fhircore/engine/pdf/HtmlPopulator.kt
agree with @ndegwamartin, let's refactor this now. I think a while loop would make sense if the substitutions we are planning may contain data that will then again need to substituted, but that does not appear to be expected here.

As @ndegwamartin suggested, let's replace the 3 while loops with a single pass over the data to perform the substitutions. I also do not think a while is what we want, because we have to do a search over the data the number of replacements we are making, i.e. suppose the length of the data is N and we are making M replacements, this runs in O(NM), we have to search the data M times, but we should be able to have it run in O(N) be doing a single pass and replacing as we see something matching the conditions for replacement

2024-05-20 15:27 UTC, pld commented on android/engine/src/main/java/org/smartregister/fhircore/engine/pdf/HtmlPopulator.kt
stated simpler, there's an algorithm for this that only requires a single pass over the HTML. I'd be ok keeping the `while` loop style, if the searches are all from start to end of the string and you are truncating (not necessarily literally, you can use offsets) the string as you e.g., one you find a match for any `@` command, you can ignore any of the string before that match on any subsequent searches b/c you've already searched it.

Alternatively, and I think preferred, it seems reasonable to scan the string from front to back iterating overs its chars, when you see an `@` collect the chars until you hit a paren then see which it matches and do your substitution into an output string.

I'd guess what's going to be more performant depends on underlying lib optimizations, but either way the requirement is you only look at each character in the string a single time

2024-06-07 15:28 UTC, pld reviewed
nice! this looks like it will be O(n)!

I don't see why there's a case where we do not increment i after going through the loop body, can you explain that?

2024-06-10 03:20 UTC, pld approved these changes

2024-06-10 13:41 UTC, pld approved these changes

2024-06-11 14:49 UTC, merged