Add a new "failed" task status for skipped vaccines dosages
opensrp/fhircore pull request #3277
Opened 2024-05-16 13:56 UTC by qaziabubakar-vd

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes [link to issue]

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2024-05-17 11:34 UTC, ellykits commented
Looks like a great addition.

2024-05-17 11:36 UTC, ellykits requested changes

2024-05-17 11:36 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirResourceUtil.kt
> +          .isIn(TaskStatus.COMPLETED, TaskStatus.FAILED)
Can you write a test for this?

2024-05-17 11:53 UTC, qaziabubakar-vd commented on android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirResourceUtil.kt
> +          .isIn(TaskStatus.COMPLETED, TaskStatus.FAILED)
Sure, I'll add a test

2024-05-21 13:21 UTC, f-odhiambo approved these changes
LGTM

2024-05-28 14:08 UTC, merged