Side Panel UI Updates
opensrp/fhircore pull request #3398
Opened 2024-07-24 07:21 UTC by aurangzaibumer

configured side menu end text color and font size along with app version font size on the SIDE PANEL

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes : https://github.com/onaio/fhir-resources/issues/3360

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2024-07-24 09:27 UTC, aurangzaibumer commented
@HenryRae @AnnieMungai please check the above screenshot for UI changes and provide feedback. 
thanks

2024-07-25 07:24 UTC, dubdabasoduba requested changes

2024-07-25 07:24 UTC, dubdabasoduba commented on android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/app/ApplicationConfiguration.kt
> +  val appVersionFontSize: Float? = null,
@ellykits @HenryRae Can we have defaults for this?

2024-07-25 07:24 UTC, dubdabasoduba commented on android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/navigation/NavigationMenuConfig.kt
> +  val countColor: String? = null,
@ellykits @HenryRae can we have defaults for this?

2024-07-25 07:57 UTC, aurangzaibumer commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/AppDrawer.kt
> +    fontSize = fontSize?.sp ?: 18.sp,
we are using default value if fontSize is null @dubdabasoduba

2024-07-25 07:57 UTC, aurangzaibumer commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/AppDrawer.kt
> +            endTextColor = navigationMenu.countColor?.parseColor() ?: Color.White,
we are using default color if countColor is null @dubdabasoduba

2024-07-25 14:18 UTC, HenryRae commented
Updates reviewed and are okay. 
- Only app version text size remaining.
Cc: @aurangzaibumer

2024-08-02 16:05 UTC, ellykits requested changes

2024-08-02 16:05 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/AppDrawer.kt
> +              navigationConfiguration.clientRegisters.isNotEmpty() &&
This is not empty check is not necessary

2024-08-02 16:05 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/AppDrawer.kt
> +            endTextColor = AppTitleColor,
Can you update the color code for the MenuItemColor instead

2024-08-02 16:05 UTC, ellykits commented on android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/components/AppDrawer.kt
> +            Column(modifier = modifier.padding(horizontal = 16.dp)) {
Isn't this adding extra horizontal padding?

2024-08-02 17:23 UTC, merged