Added Configurable Date Format For App
opensrp/fhircore pull request #3554
Opened 2024-10-09 22:57 UTC by aurangzaibumer

added date format configurable and applied on sync time in navigation, setting screen and insight screen

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes : https://github.com/opensrp/fhircore/issues/3472

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

2024-10-15 10:04 UTC, dubdabasoduba commented
@marklosh @Lentumunai-Mark  This seems to work well

![date-app-version](https://github.com/user-attachments/assets/72d639cd-5d4c-46fe-af6b-eedda4f030fd)
![date-insights-page](https://github.com/user-attachments/assets/2ede3cc5-7b30-4ba3-b693-bcf31bb34b71)
![date-sync-bar](https://github.com/user-attachments/assets/0ea184dd-d949-40fc-aea7-5991c25c6c2e)

2024-10-17 15:38 UTC, ellykits requested changes

2024-10-17 15:38 UTC, ellykits commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModelTest.kt
> +    every { appMainViewModel.applicationConfiguration.dateFormat } returns "yyyy-MM-dd HH:mm:ss"
It is not necessary to mock this. Save and use the timestamp instead.

2024-10-17 15:38 UTC, ellykits commented on android/quest/src/test/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModelTest.kt
> +    every { appMainViewModel.applicationConfiguration.dateFormat } returns "yyyy-MM-dd"
It is not necessary to mock this. Save and use the timestamp instead.

2024-10-17 17:30 UTC, merged

2024-10-17 18:46 UTC, aurangzaibumer commented
Thank you for merging this PR.