- ANC details screen
opensrp/fhircore pull request #515
Opened 2021-09-04 12:23 UTC by RaaziaTarique

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #286 

**Type**
Choose one: (Feature) 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2021-09-06 05:38 UTC, RaaziaTarique commented
@ellykits please review this PR.

2021-09-06 08:06 UTC, ellykits requested changes

2021-09-06 08:06 UTC, ellykits commented on android/anc/src/main/java/org/smartregister/fhircore/anc/ui/anccare/register/AncItemMapper.kt
> +    val gender = dto.extractGender().first()
Removing the context will not allow for translation.

2021-09-06 08:06 UTC, ellykits commented on android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/PatientExtension.kt
> +fun Patient.extractGender() =
Removing context would not allow for translation. Suggestion is to have the text in `string.xml` file then pick the first letter. Example **Female**  is translated to **Kvenkyns**  in Icelandic (courtesy of Google translate). The first letters are not the same.

2021-09-06 08:24 UTC, RaaziaTarique commented on android/anc/src/main/AndroidManifest.xml
> +        <activity android:name=".ui.anccare.details.AncDetailsActivity" />
I am the theme at Application level

2021-09-06 10:22 UTC, RaaziaTarique commented on android/anc/src/main/java/org/smartregister/fhircore/anc/ui/anccare/details/CarePlanAdapter.kt
> +class CarePlanAdapter :
I don't see that we'll be needing pagination for this adapter.

2021-09-08 08:25 UTC, ellykits requested changes

2021-09-08 08:25 UTC, ellykits commented on android/anc/src/main/java/org/smartregister/fhircore/anc/ui/anccare/details/AncPatientItemMapper.kt
> +    if (!hasBirthDate()) return ""
Can we refactor these implementations as extensions and keep them in the file named `PatientExtension`. Do the refactor too for `PatientItemMapper` in eir application module

2021-09-08 13:25 UTC, ellykits approved these changes
:+1: LGTM

2021-09-08 13:26 UTC, merged