Update StructureMap and Questionnaire for patient-registration
opensrp/fhircore pull request #542
Opened 2021-09-13 18:30 UTC by ekigamba

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #185

**Type**
Choose one: Feature

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2021-09-17 14:19 UTC, pld requested changes

2021-09-17 14:19 UTC, pld commented on android/eir/src/test/java/org/smartregister/fhircore/ResourceExtensionTest.kt
> +/** Created by Ephraim Kigamba - nek.eam@gmail.com on 13-09-2021. */
remove

2021-09-17 14:19 UTC, pld commented on android/eir/src/test/java/org/smartregister/fhircore/engine/StructureMapTestUtilities.kt
> +    /*try {
what's up w/this?

2021-09-17 14:19 UTC, pld commented on android/eir/src/test/java/org/smartregister/fhircore/engine/data/local/DefaultRepositoryTest.kt
> +/** Created by Ephraim Kigamba - nek.eam@gmail.com on 15-09-2021. */
remove throughout

2021-09-20 06:53 UTC, ndegwamartin submitted a review, later dismissed

2021-09-20 09:20 UTC, ndegwamartin submitted a review, later dismissed

2021-09-20 13:22 UTC, pld submitted a review, later dismissed

2021-09-20 16:10 UTC, pld submitted a review, later dismissed

2021-09-21 08:59 UTC, ndegwamartin approved these changes

2021-09-21 09:16 UTC, merged