Added Measure reporting to anc application
opensrp/fhircore pull request #601
Opened 2021-10-04 09:38 UTC by kimigxfoxy

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #177

**Type**
Choose one: (Feature) 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2021-10-04 12:07 UTC, ellykits requested changes

2021-10-04 12:07 UTC, ellykits commented on android/anc/src/main/java/org/smartregister/fhircore/anc/ui/anccare/details/AncDetailsViewModel.kt
> +    MEASURE_URL: String
Change the casing for these variable to `camelCase`

2021-10-04 12:07 UTC, ellykits commented on android/anc/src/main/java/org/smartregister/fhircore/anc/ui/anccare/details/AncDetailsFragment.kt
>    var PATIENT_URL = ""
Why do we have empty string constants?

2021-10-04 18:04 UTC, pld approved these changes

2021-10-05 12:05 UTC, ellykits approved these changes

2021-10-05 12:11 UTC, ndegwamartin commented on CHANGELOG.md
> +- Added measure reporting to ANC application
Please add the module name separated by a pipe character as a prefix to all change log entries

2021-10-05 12:15 UTC, merged