675 measure report feedback1
opensrp/fhircore pull request #783
Opened 2021-11-23 05:21 UTC by AbdulWahabMemon

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[675] 

**Type**
Bug fix | Feature

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2021-11-23 14:27 UTC, kimigxfoxy commented
Looks good

2021-11-23 14:29 UTC, kimigxfoxy requested changes
Looks good. @AbdulWahabMemon  You can update changelog.md

2021-11-23 20:41 UTC, AbdulWahabMemon commented
> Looks good. @AbdulWahabMemon You can update changelog.md

updated

2021-11-24 03:52 UTC, kimigxfoxy approved these changes

2021-11-24 05:52 UTC, kimigxfoxy approved these changes

2021-11-24 05:55 UTC, merged