- Edit info redirection added on PatientDetailsActivity.kt
opensrp/fhircore pull request #810
Opened 2021-12-01 10:41 UTC by RaaziaTarique

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #765 

**Type**
Choose one: Feature

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2021-12-03 17:34 UTC, pld approved these changes

2021-12-06 13:50 UTC, ekigamba requested changes

2021-12-06 13:50 UTC, ekigamba commented on android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/ResourceExtension.kt
> +      this.extension = this@updateFrom.extension
Fix this so that we merge both incase new extension are added

2021-12-06 13:50 UTC, ekigamba commented on android/anc/src/test/java/org/smartregister/fhircore/anc/data/family/FamilyRepositoryTest.kt
> +    coVerify { resourceMapperExtended.saveParsedResource(any(), any(), any(), "1111", eq(true)) }
Verify that the Questionnaire() and QuestionnaireResponse() passed on line 127 are the same here

2021-12-06 13:50 UTC, ekigamba commented on android/anc/src/test/java/org/smartregister/fhircore/anc/data/family/FamilyRepositoryTest.kt
> +  fun updateProcessFamilyMemberShouldExtractEntities() = runBlockingTest {
Rename to `updateProcessFamilyMemberShouldCallSaveParsedResourceWithEditBooleanAsTrue`

2021-12-06 13:50 UTC, ekigamba commented on android/anc/src/test/java/org/smartregister/fhircore/anc/data/family/FamilyRepositoryTest.kt
> +    coVerify { resourceMapperExtended.saveParsedResource(any(), any(), any(), null, eq(true)) }
Verify that the Questionnaire() and QuestionnaireResponse() passed on line 141 are the same here

2021-12-06 13:50 UTC, ekigamba commented on android/anc/src/test/java/org/smartregister/fhircore/anc/data/family/FamilyRepositoryTest.kt
> +  fun updateProcessFamilyHeadShouldExtractEntities() = runBlockingTest {
Similary, rename this test to indicate that we are only verifing the `saveParsedResource` method is called with the edit flag as true

2021-12-06 13:50 UTC, ekigamba commented on android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/ResourceExtension.kt
> +      this.extension = this@updateFrom.extension
You can also add tests for this new functionality so that it's caught by the tests if it breaks

2021-12-07 13:59 UTC, ekigamba commented on android/anc/src/test/java/org/smartregister/fhircore/anc/data/family/FamilyRepositoryTest.kt
> +    coVerify { resourceMapperExtended.saveParsedResource(any(), any(), any(), null, eq(true)) }
Assign the Questionnaire and QuestionnaireResponse to variables and then verify them as below

```
coVerify { resourceMapperExtended.saveParsedResource(questionnaireResponse, questionnaire, any(), null, true) }
```

2021-12-10 11:55 UTC, pld approved these changes

2021-12-13 15:32 UTC, pld submitted a review, later dismissed

2021-12-15 19:20 UTC, pld approved these changes

2021-12-15 19:35 UTC, merged