Implement StructureMap extraction for CHW ANC BMI questionnaire
opensrp/fhircore pull request #926
Opened 2022-01-04 09:48 UTC by ekigamba

Fixes #897

**Type**
Choose one: Code health

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

2022-01-14 19:00 UTC, pld commented
is this still relevant? If so, can we finish it up

2022-01-17 06:13 UTC, ekigamba commented
> is this still relevant? If so, can we finish it up

Cool

2022-03-01 15:37 UTC, RaaziaTarique approved these changes
LGTM

2022-03-01 16:00 UTC, RaaziaTarique requested changes

2022-03-02 15:11 UTC, ekigamba commented on android/anc/src/main/java/org/smartregister/fhircore/anc/ui/details/bmicompute/BmiQuestionnaireActivity.kt
> +      val bundle =
I have fixed the height observation not having the `Obs.effective`. This was missing for the standard measurement

2022-03-02 15:11 UTC, ekigamba commented on android/anc/src/main/java/org/smartregister/fhircore/anc/ui/details/bmicompute/BmiQuestionnaireActivity.kt
> +      val bundle =
I have also uploaded the new StructureMap

2022-03-03 08:38 UTC, RaaziaTarique submitted a review, later dismissed

2022-03-03 09:13 UTC, RaaziaTarique approved these changes

2022-03-03 09:13 UTC, merged